### ISSUE TITLE
Re-Focus Note after Date / Time insert

### ISSUE THREAD

**Issue by Glint-Eye** [joycode-hub/datepicker-plugin#10]
Right now I lose focus after inserting any Date, Time, Date Time entry. After a "Focus on last Note" command the cursor jumps to the beginning of the just inserted entry.

It would be great if a Date / Time insertion automatically refocuses the note and move the cursor to the end of the just inserted Date / Time.

**Comment by joycode-hub** [comment]
This is now fixed in release 0.3.24
