### ISSUE TITLE
Insert date not working

### ISSUE THREAD

**Issue by aikruger** [joycode-hub/datepicker-plugin#2]
I am not sure if I understand how this add-in works but it does not seem to insert an actual date picked. Also the pop calendar is positioned  top left of obsidian, is it possible to make it float near curser rather?
Thanks

**Comment by joycode-hub** [comment]
Do you have the latest release (currently 0.3.8) installed?

**Comment by aikruger** [comment]
Yes

**Comment by joycode-hub** [comment]
Does this only happen when using the calendar?

Also, do you have the "Immediately show calendar" set to yes/true in the plugin settings?

![image](https://github.com/user-attachments/assets/47135311-4641-42b0-96ed-75b3c1c982e8)

**Comment by aikruger** [comment]
It is the same whether I have immediately show calendar on or off. I select the calendar date and then nothing happens

**Comment by joycode-hub** [comment]
Can you please check if this is fixed in the latest release? (0.3.10)

**Comment by joycode-hub** [comment]
Yes I believe I see the issue now, I will work on a fix.

**Comment by joycode-hub** [comment]
I found the issue you referred to and fixed it in release 0.3.13.
The insert command did indeed have a bug introduced by previous changes. 

Please let me know if you have any other comments before I close this issue.

**Comment by aikruger** [comment]
It works brilliantly now, and renders well. Many thanks
