### ISSUE TITLE
Feature request: Specific format for date

### ISSUE THREAD

**Issue by jcesguerram** [joycode-hub/datepicker-plugin#3]
Hi! Very cool plugin, thanks!
Would it be possible to add a feature so that ypu could choose from some format options to insert the date? For example in bold font or as H2 heading.
... I realize this is pretty easy to add 'by hand', I just think it would be a cool little feature

**Comment by joycode-hub** [comment]
Hi,
Thank you for the suggestion. I believe that formatting the date text falls outside the scope of this plugin. There are numerous methods to edit text formatting in Obsidian, such as using built-in commands like Toggle bold, heading, strikethrough, etc., and there are also several plugins available that facilitate easy text formatting.
However, a potentially useful feature would be to add a setting that allows the date picker to automatically select the entire date text. This would streamline the process of applying any formatting to the date text using the methods mentioned above.

**Comment by joycode-hub** [comment]
I added a new setting to the plugin: Select date/time text in release 0.3.19. Although not full formatting support, I believe it can make formatting quicker and easier.
Please let me know if you have any comments before I close this issue.

**Comment by jcesguerram** [comment]
> I added a new setting to the plugin: Select date/time text in release 0.3.19. Although not full formatting support, I believe it can make formatting quicker and easier. Please let me know if you have any comments before I close this issue.

yeah that *is* very useful, thanks!
