### ISSUE TITLE
Feature request: Ability to add only time

### ISSUE THREAD

**Issue by atharva-upadhye** [joycode-hub/datepicker-plugin#4]
I would like to be able to add only time in preferred selected format from command palette.
It's important to not prefix with date. In plugins like [Day Planner](https://github.com/ivan-lednev/obsidian-day-planner) it is required to put time in the front like this: `- [ ] 10:00 - 10:30 Wake up`

**Comment by joycode-hub** [comment]
Feature implemented in release 0.3.19.
Please let me know if you have any comments.

**Comment by Moyf** [comment]
> Feature implemented in release 0.3.19. Please let me know if you have any comments.

Hi~ Can you seperate the options for "date" and "time" ?
![image](https://github.com/user-attachments/assets/de7440f4-7d30-49db-ab3f-4377922a991f)

I have my own css snippets for time text so don't want to show the icon for time, meanwhile I wish to keep the icon for date 😄

---

Additionally, if [date (date+time)] & [time only] are seperated, maybe you can also consider using different icons for ⏰ time only ?

**Comment by joycode-hub** [comment]
> Hi~ Can you seperate the options for "date" and "time" ?

> Additionally, if [date (date+time)] & [time only] are seperated, maybe you can also consider using different icons for ⏰ time only ?

Implemented in release 0.3.20

**Comment by Moyf** [comment]
> > Hi~ Can you seperate the options for "date" and "time" ?
> 
> ![image](https://private-user-images.githubusercontent.com/174064239/352874837-3ce89581-6650-4de6-a8e7-e0fa25498713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjA5MjUsIm5iZiI6MTcyMjIyMDYyNSwicGF0aCI6Ii8xNzQwNjQyMzkvMzUyODc0ODM3LTNjZTg5NTgxLTY2NTAtNGRlNi1hOGU3LWUwZmEyNTQ5ODcxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMjM3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjI4NjU4NDgxM2MwMzk5ZjBkNGJkNTYxNTYyZmU4Yjc2ZDRlMzFkYmZiMDYyOTM2YmE1M2QwMDg0NDcyZWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RatMWwSFSFkYr4V_veZF3VRXlkgLf05PzJ26hml8D-E)
> 
> > Additionally, if [date (date+time)] & [time only] are seperated, maybe you can also consider using different icons for ⏰ time only ?
> 
> ![image](https://private-user-images.githubusercontent.com/174064239/352874781-cf42c171-ca75-4b60-9ca5-2ed562c12a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjA5MjUsIm5iZiI6MTcyMjIyMDYyNSwicGF0aCI6Ii8xNzQwNjQyMzkvMzUyODc0NzgxLWNmNDJjMTcxLWNhNzUtNGI2MC05Y2E1LTJlZDU2MmMxMmE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMjM3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjliMjZkYjllN2U1MzIwNGUwZGViM2I5YjA1OTY5ODMxMTRkOWMwMWI3Yjg5ODc2ZTgyMmRmYTA3ZTM0NmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wpNzCz2w4T406YTdPIipXi56a_GKCb3ccxYv4QOnOAE)
> 
> Implemented in release 0.3.20

That's really good! thank you!
