### ISSUE TITLE
Bug with other date and time formats

### ISSUE THREAD

**Issue by alibeksabyr** [joycode-hub/datepicker-plugin#9]
I tried changing the date format in the main.js file. It turned out like this: I changed all formats from YYYY-MM-DD to DD.MM.YYYY. 

The date format has broken with time, and shows the day separately from everyone else. If you edit the date, but the day is duplicated.

![obsidian-datepicker-dateformat-problem](https://github.com/user-attachments/assets/dce9d11b-db0b-477c-ba2b-2d67c0b3b1a0)

Is it possible to somehow solve this by changing a few lines of code? I'm not very good at this, unfortunately 😊

**Comment by joycode-hub** [comment]
> I tried changing the date format in the main.js file. It turned out like this: I changed all formats from YYYY-MM-DD to DD.MM.YYYY

I think you only need to change all occurrences of:
formatToUser: "DD-MM-YYYY hh:mm A",
formatToUser: "DD-MM-YYYY HH:mm",
formatToUser: "DD-MM-YYYY" ,

To:
formatToUser: "DD.MM.YYYY hh:mm A",
formatToUser: "DD.MM.YYYY HH:mm",
formatToUser: "DD.MM.YYYY" ,

**Comment by alibeksabyr** [comment]
Unfortunately, this method did not help me. The problem lies in the commands `"Insert current date and time"` and `"Insert new date and time"`. I changed the format there too, but it still doesn't work. **Everything breaks because DD is in front MM.YYYY**

**Comment by romanskorobagatko** [comment]
@joycode-hub Could you please add an option to choose a date format? For example I'd like to use "MM-DD-YYYY".

**Comment by TonyAtlas** [comment]
Also need the ability to select the date format. If possible, please add such function.

**Comment by joycode-hub** [comment]
I have added the ability to select a date format in release 0.3.24, thank you for your patience.
